services:
  - type: web
    name: tanta-delivery-bot
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
